### PR TITLE
Merging staging-app2 in to master.

### PR DESCRIPTION
**Pull request by ushankar208**

### CODE REVIEW

**Comment by oh-frontend** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **ushankar208**
You can assign the PR to them by writing `/assign @ushankar208` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=scheduleonce%2Fng-strictify).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/scheduleonce/ng-strictify/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Review by oh-rahulsingla — APPROVED** [review]

**Comment by oh-frontend** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *[oh-rahulsingla](https://github.com/scheduleonce/ng-strictify/pull/53#pullrequestreview-1235510531 "Approved")*
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **ushankar208**
You can assign the PR to them by writing `/assign @ushankar208` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=scheduleonce%2Fng-strictify).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/scheduleonce/ng-strictify/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Review by SO-ashusrivastava — APPROVED** [review]

**Comment by so-frontend-integrations** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[oh-rahulsingla](https://github.com/scheduleonce/ng-strictify/pull/53#pullrequestreview-1235510531 "Approved")*, *[SO-ashusrivastava](https://github.com/scheduleonce/ng-strictify/pull/53#pullrequestreview-1235524508 "Approved")*

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=scheduleonce%2Fng-strictify).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/scheduleonce/ng-strictify/blob/master/OWNERS)~~ [SO-ashusrivastava]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by so-frontend-integrations** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[oh-rahulsingla](https://github.com/scheduleonce/ng-strictify/pull/53#pullrequestreview-1235510531 "Approved")*, *[SO-ashusrivastava](https://github.com/scheduleonce/ng-strictify/pull/53#pullrequestreview-1235524508 "Approved")*

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=scheduleonce%2Fng-strictify).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/scheduleonce/ng-strictify/blob/master/OWNERS)~~ [SO-ashusrivastava]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Review by raghavaggarwalOH — APPROVED** [review]

**Comment by so-frontend-integrations** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[oh-rahulsingla](https://github.com/scheduleonce/ng-strictify/pull/53#pullrequestreview-1235510531 "Approved")*, *[raghavaggarwalOH](https://github.com/scheduleonce/ng-strictify/pull/53#pullrequestreview-1235531922 "Approved")*, *[SO-ashusrivastava](https://github.com/scheduleonce/ng-strictify/pull/53#pullrequestreview-1235524508 "Approved")*

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=scheduleonce%2Fng-strictify).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/scheduleonce/ng-strictify/blob/master/OWNERS)~~ [SO-ashusrivastava]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Review by SO-jagjeetsingh — APPROVED** [review]
Nothing from Stark here.

**Comment by so-frontend-integrations** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[oh-rahulsingla](https://github.com/scheduleonce/ng-strictify/pull/53#pullrequestreview-1235510531 "Approved")*, *[raghavaggarwalOH](https://github.com/scheduleonce/ng-strictify/pull/53#pullrequestreview-1235531922 "Approved")*, *[SO-ashusrivastava](https://github.com/scheduleonce/ng-strictify/pull/53#pullrequestreview-1235524508 "Approved")*, *[SO-jagjeetsingh](https://github.com/scheduleonce/ng-strictify/pull/53#pullrequestreview-1235533299 "Approved")*

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=scheduleonce%2Fng-strictify).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/scheduleonce/ng-strictify/blob/master/OWNERS)~~ [SO-ashusrivastava]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Review by ApoorvaSrivastava — APPROVED** [review]
Nothing from Team Graphene

**Comment by so-integrations** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[ApoorvaSrivastava](https://github.com/scheduleonce/ng-strictify/pull/53#pullrequestreview-1235546696 "Approved")*, *[oh-rahulsingla](https://github.com/scheduleonce/ng-strictify/pull/53#pullrequestreview-1235510531 "Approved")*, *[raghavaggarwalOH](https://github.com/scheduleonce/ng-strictify/pull/53#pullrequestreview-1235531922 "Approved")*, *[SO-ashusrivastava](https://github.com/scheduleonce/ng-strictify/pull/53#pullrequestreview-1235524508 "Approved")*, *[SO-jagjeetsingh](https://github.com/scheduleonce/ng-strictify/pull/53#pullrequestreview-1235533299 "Approved")*

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=scheduleonce%2Fng-strictify).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/scheduleonce/ng-strictify/blob/master/OWNERS)~~ [SO-ashusrivastava]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Review by sampada-ojha — APPROVED** [review]

**Review by vinaykumar01 — APPROVED** [review]

**Comment by so-integrations** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[ApoorvaSrivastava](https://github.com/scheduleonce/ng-strictify/pull/53#pullrequestreview-1235546696 "Approved")*, *[oh-rahulsingla](https://github.com/scheduleonce/ng-strictify/pull/53#pullrequestreview-1235510531 "Approved")*, *[raghavaggarwalOH](https://github.com/scheduleonce/ng-strictify/pull/53#pullrequestreview-1235531922 "Approved")*, *[sampada-ojha](https://github.com/scheduleonce/ng-strictify/pull/53#pullrequestreview-1235547393 "Approved")*, *[SO-ashusrivastava](https://github.com/scheduleonce/ng-strictify/pull/53#pullrequestreview-1235524508 "Approved")*, *[SO-jagjeetsingh](https://github.com/scheduleonce/ng-strictify/pull/53#pullrequestreview-1235533299 "Approved")*, *[vinaykumar01](https://github.com/scheduleonce/ng-strictify/pull/53#pullrequestreview-1235547608 "Approved")*

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=scheduleonce%2Fng-strictify).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/scheduleonce/ng-strictify/blob/master/OWNERS)~~ [SO-ashusrivastava,vinaykumar01]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Review by vaibhavso — APPROVED** [review]

**Comment by oh-frontend** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[ApoorvaSrivastava](https://github.com/scheduleonce/ng-strictify/pull/53#pullrequestreview-1235546696 "Approved")*, *[oh-rahulsingla](https://github.com/scheduleonce/ng-strictify/pull/53#pullrequestreview-1235510531 "Approved")*, *[raghavaggarwalOH](https://github.com/scheduleonce/ng-strictify/pull/53#pullrequestreview-1235531922 "Approved")*, *[sampada-ojha](https://github.com/scheduleonce/ng-strictify/pull/53#pullrequestreview-1235547393 "Approved")*, *[SO-ashusrivastava](https://github.com/scheduleonce/ng-strictify/pull/53#pullrequestreview-1235524508 "Approved")*, *[SO-jagjeetsingh](https://github.com/scheduleonce/ng-strictify/pull/53#pullrequestreview-1235533299 "Approved")*, *[vaibhavso](https://github.com/scheduleonce/ng-strictify/pull/53#pullrequestreview-1235587953 "Approved")*, *[vinaykumar01](https://github.com/scheduleonce/ng-strictify/pull/53#pullrequestreview-1235547608 "Approved")*

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=scheduleonce%2Fng-strictify).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/scheduleonce/ng-strictify/blob/master/OWNERS)~~ [SO-ashusrivastava,vaibhavso,vinaykumar01]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Review by bharatsinghoh — APPROVED** [review]

**Comment by so-frontend-integrations** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[ApoorvaSrivastava](https://github.com/scheduleonce/ng-strictify/pull/53#pullrequestreview-1235546696 "Approved")*, *[bharatsinghoh](https://github.com/scheduleonce/ng-strictify/pull/53#pullrequestreview-1235604894 "Approved")*, *[oh-rahulsingla](https://github.com/scheduleonce/ng-strictify/pull/53#pullrequestreview-1235510531 "Approved")*, *[raghavaggarwalOH](https://github.com/scheduleonce/ng-strictify/pull/53#pullrequestreview-1235531922 "Approved")*, *[sampada-ojha](https://github.com/scheduleonce/ng-strictify/pull/53#pullrequestreview-1235547393 "Approved")*, *[SO-ashusrivastava](https://github.com/scheduleonce/ng-strictify/pull/53#pullrequestreview-1235524508 "Approved")*, *[SO-jagjeetsingh](https://github.com/scheduleonce/ng-strictify/pull/53#pullrequestreview-1235533299 "Approved")*, *[vaibhavso](https://github.com/scheduleonce/ng-strictify/pull/53#pullrequestreview-1235587953 "Approved")*, *[vinaykumar01](https://github.com/scheduleonce/ng-strictify/pull/53#pullrequestreview-1235547608 "Approved")*

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=scheduleonce%2Fng-strictify).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/scheduleonce/ng-strictify/blob/master/OWNERS)~~ [SO-ashusrivastava,vaibhavso,vinaykumar01]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Review by UpenderOH — APPROVED** [review]

**Comment by so-frontend-integrations** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[ApoorvaSrivastava](https://github.com/scheduleonce/ng-strictify/pull/53#pullrequestreview-1235546696 "Approved")*, *[bharatsinghoh](https://github.com/scheduleonce/ng-strictify/pull/53#pullrequestreview-1235604894 "Approved")*, *[oh-rahulsingla](https://github.com/scheduleonce/ng-strictify/pull/53#pullrequestreview-1235510531 "Approved")*, *[raghavaggarwalOH](https://github.com/scheduleonce/ng-strictify/pull/53#pullrequestreview-1235531922 "Approved")*, *[sampada-ojha](https://github.com/scheduleonce/ng-strictify/pull/53#pullrequestreview-1235547393 "Approved")*, *[SO-ashusrivastava](https://github.com/scheduleonce/ng-strictify/pull/53#pullrequestreview-1235524508 "Approved")*, *[SO-jagjeetsingh](https://github.com/scheduleonce/ng-strictify/pull/53#pullrequestreview-1235533299 "Approved")*, *[UpenderOH](https://github.com/scheduleonce/ng-strictify/pull/53#pullrequestreview-1235606576 "Approved")*, *[vaibhavso](https://github.com/scheduleonce/ng-strictify/pull/53#pullrequestreview-1235587953 "Approved")*, *[vinaykumar01](https://github.com/scheduleonce/ng-strictify/pull/53#pullrequestreview-1235547608 "Approved")*

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=scheduleonce%2Fng-strictify).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/scheduleonce/ng-strictify/blob/master/OWNERS)~~ [SO-ashusrivastava,vaibhavso,vinaykumar01]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Review by neetuoncehub — APPROVED** [review]

**Comment by so-integrations** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[ApoorvaSrivastava](https://github.com/scheduleonce/ng-strictify/pull/53#pullrequestreview-1235546696 "Approved")*, *[bharatsinghoh](https://github.com/scheduleonce/ng-strictify/pull/53#pullrequestreview-1235604894 "Approved")*, *[neetuoncehub](https://github.com/scheduleonce/ng-strictify/pull/53#pullrequestreview-1235627962 "Approved")*, *[oh-rahulsingla](https://github.com/scheduleonce/ng-strictify/pull/53#pullrequestreview-1235510531 "Approved")*, *[raghavaggarwalOH](https://github.com/scheduleonce/ng-strictify/pull/53#pullrequestreview-1235531922 "Approved")*, *[sampada-ojha](https://github.com/scheduleonce/ng-strictify/pull/53#pullrequestreview-1235547393 "Approved")*, *[SO-ashusrivastava](https://github.com/scheduleonce/ng-strictify/pull/53#pullrequestreview-1235524508 "Approved")*, *[SO-jagjeetsingh](https://github.com/scheduleonce/ng-strictify/pull/53#pullrequestreview-1235533299 "Approved")*, *[UpenderOH](https://github.com/scheduleonce/ng-strictify/pull/53#pullrequestreview-1235606576 "Approved")*, *[vaibhavso](https://github.com/scheduleonce/ng-strictify/pull/53#pullrequestreview-1235587953 "Approved")*, *[vinaykumar01](https://github.com/scheduleonce/ng-strictify/pull/53#pullrequestreview-1235547608 "Approved")*

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=scheduleonce%2Fng-strictify).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/scheduleonce/ng-strictify/blob/master/OWNERS)~~ [SO-ashusrivastava,vaibhavso,vinaykumar01]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Pull request merged**
