### PR TITLE
Merging staging-app2 in to master.

### PR DESCRIPTION
**Pull request by ushankar208**

### CODE REVIEW

**Comment by oh-integrations** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **ushankar208**
You can assign the PR to them by writing `/assign @ushankar208` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=scheduleonce%2Fng-strictify).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/scheduleonce/ng-strictify/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Review by SO-ashusrivastava — APPROVED** [review]

**Comment by oh-integrations** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[SO-ashusrivastava](https://github.com/scheduleonce/ng-strictify/pull/69#pullrequestreview-1892581918 "Approved")*

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=scheduleonce%2Fng-strictify).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/scheduleonce/ng-strictify/blob/master/OWNERS)~~ [SO-ashusrivastava]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Review by soSkumar — APPROVED** [review]

**Comment by oh-integrations** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[SO-ashusrivastava](https://github.com/scheduleonce/ng-strictify/pull/69#pullrequestreview-1892581918 "Approved")*, *[soSkumar](https://github.com/scheduleonce/ng-strictify/pull/69#pullrequestreview-1892582331 "Approved")*

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=scheduleonce%2Fng-strictify).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/scheduleonce/ng-strictify/blob/master/OWNERS)~~ [SO-ashusrivastava]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by oh-integrations** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[SO-ashusrivastava](https://github.com/scheduleonce/ng-strictify/pull/69#pullrequestreview-1892581918 "Approved")*, *[soSkumar](https://github.com/scheduleonce/ng-strictify/pull/69#pullrequestreview-1892582331 "Approved")*

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=scheduleonce%2Fng-strictify).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/scheduleonce/ng-strictify/blob/master/OWNERS)~~ [SO-ashusrivastava]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Review by ApoorvaSrivastava — APPROVED** [review]

**Comment by oh-integrations** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[ApoorvaSrivastava](https://github.com/scheduleonce/ng-strictify/pull/69#pullrequestreview-1892589015 "Approved")*, *[SO-ashusrivastava](https://github.com/scheduleonce/ng-strictify/pull/69#pullrequestreview-1892581918 "Approved")*, *[soSkumar](https://github.com/scheduleonce/ng-strictify/pull/69#pullrequestreview-1892582331 "Approved")*

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=scheduleonce%2Fng-strictify).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/scheduleonce/ng-strictify/blob/master/OWNERS)~~ [SO-ashusrivastava]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Review by vaibhavso — APPROVED** [review]

**Comment by oh-integrations** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[ApoorvaSrivastava](https://github.com/scheduleonce/ng-strictify/pull/69#pullrequestreview-1892589015 "Approved")*, *[SO-ashusrivastava](https://github.com/scheduleonce/ng-strictify/pull/69#pullrequestreview-1892581918 "Approved")*, *[soSkumar](https://github.com/scheduleonce/ng-strictify/pull/69#pullrequestreview-1892582331 "Approved")*, *[vaibhavso](https://github.com/scheduleonce/ng-strictify/pull/69#pullrequestreview-1892609440 "Approved")*

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=scheduleonce%2Fng-strictify).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/scheduleonce/ng-strictify/blob/master/OWNERS)~~ [SO-ashusrivastava,vaibhavso]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Review by so-kushal — APPROVED** [review]

**Comment by oh-integrations** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[ApoorvaSrivastava](https://github.com/scheduleonce/ng-strictify/pull/69#pullrequestreview-1892589015 "Approved")*, *[SO-ashusrivastava](https://github.com/scheduleonce/ng-strictify/pull/69#pullrequestreview-1892581918 "Approved")*, *[so-kushal](https://github.com/scheduleonce/ng-strictify/pull/69#pullrequestreview-1892649478 "Approved")*, *[soSkumar](https://github.com/scheduleonce/ng-strictify/pull/69#pullrequestreview-1892582331 "Approved")*, *[vaibhavso](https://github.com/scheduleonce/ng-strictify/pull/69#pullrequestreview-1892609440 "Approved")*

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=scheduleonce%2Fng-strictify).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/scheduleonce/ng-strictify/blob/master/OWNERS)~~ [SO-ashusrivastava,vaibhavso]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Review by bharatsinghoh — APPROVED** [review]

**Comment by oh-integrations** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[ApoorvaSrivastava](https://github.com/scheduleonce/ng-strictify/pull/69#pullrequestreview-1892589015 "Approved")*, *[bharatsinghoh](https://github.com/scheduleonce/ng-strictify/pull/69#pullrequestreview-1892651118 "Approved")*, *[SO-ashusrivastava](https://github.com/scheduleonce/ng-strictify/pull/69#pullrequestreview-1892581918 "Approved")*, *[so-kushal](https://github.com/scheduleonce/ng-strictify/pull/69#pullrequestreview-1892649478 "Approved")*, *[soSkumar](https://github.com/scheduleonce/ng-strictify/pull/69#pullrequestreview-1892582331 "Approved")*, *[vaibhavso](https://github.com/scheduleonce/ng-strictify/pull/69#pullrequestreview-1892609440 "Approved")*

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=scheduleonce%2Fng-strictify).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/scheduleonce/ng-strictify/blob/master/OWNERS)~~ [SO-ashusrivastava,vaibhavso]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Review by SO-jagjeetsingh — APPROVED** [review]

**Comment by oh-integrations** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[ApoorvaSrivastava](https://github.com/scheduleonce/ng-strictify/pull/69#pullrequestreview-1892589015 "Approved")*, *[bharatsinghoh](https://github.com/scheduleonce/ng-strictify/pull/69#pullrequestreview-1892651118 "Approved")*, *[SO-ashusrivastava](https://github.com/scheduleonce/ng-strictify/pull/69#pullrequestreview-1892581918 "Approved")*, *[SO-jagjeetsingh](https://github.com/scheduleonce/ng-strictify/pull/69#pullrequestreview-1892658645 "Approved")*, *[so-kushal](https://github.com/scheduleonce/ng-strictify/pull/69#pullrequestreview-1892649478 "Approved")*, *[soSkumar](https://github.com/scheduleonce/ng-strictify/pull/69#pullrequestreview-1892582331 "Approved")*, *[vaibhavso](https://github.com/scheduleonce/ng-strictify/pull/69#pullrequestreview-1892609440 "Approved")*

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=scheduleonce%2Fng-strictify).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/scheduleonce/ng-strictify/blob/master/OWNERS)~~ [SO-ashusrivastava,vaibhavso]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Review by neetuoncehub — APPROVED** [review]

**Review by raghavaggarwalOH — APPROVED** [review]

**Comment by oh-integrations** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[ApoorvaSrivastava](https://github.com/scheduleonce/ng-strictify/pull/69#pullrequestreview-1892589015 "Approved")*, *[bharatsinghoh](https://github.com/scheduleonce/ng-strictify/pull/69#pullrequestreview-1892651118 "Approved")*, *[neetuoncehub](https://github.com/scheduleonce/ng-strictify/pull/69#pullrequestreview-1892705575 "Approved")*, *[raghavaggarwalOH](https://github.com/scheduleonce/ng-strictify/pull/69#pullrequestreview-1892830283 "Approved")*, *[SO-ashusrivastava](https://github.com/scheduleonce/ng-strictify/pull/69#pullrequestreview-1892581918 "Approved")*, *[SO-jagjeetsingh](https://github.com/scheduleonce/ng-strictify/pull/69#pullrequestreview-1892658645 "Approved")*, *[so-kushal](https://github.com/scheduleonce/ng-strictify/pull/69#pullrequestreview-1892649478 "Approved")*, *[soSkumar](https://github.com/scheduleonce/ng-strictify/pull/69#pullrequestreview-1892582331 "Approved")*, *[vaibhavso](https://github.com/scheduleonce/ng-strictify/pull/69#pullrequestreview-1892609440 "Approved")*

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=scheduleonce%2Fng-strictify).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/scheduleonce/ng-strictify/blob/master/OWNERS)~~ [SO-ashusrivastava,vaibhavso]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Review by so-kaushal — APPROVED** [review]

**Comment by oh-integrations** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[ApoorvaSrivastava](https://github.com/scheduleonce/ng-strictify/pull/69#pullrequestreview-1892589015 "Approved")*, *[bharatsinghoh](https://github.com/scheduleonce/ng-strictify/pull/69#pullrequestreview-1892651118 "Approved")*, *[neetuoncehub](https://github.com/scheduleonce/ng-strictify/pull/69#pullrequestreview-1892705575 "Approved")*, *[raghavaggarwalOH](https://github.com/scheduleonce/ng-strictify/pull/69#pullrequestreview-1892830283 "Approved")*, *[SO-ashusrivastava](https://github.com/scheduleonce/ng-strictify/pull/69#pullrequestreview-1892581918 "Approved")*, *[SO-jagjeetsingh](https://github.com/scheduleonce/ng-strictify/pull/69#pullrequestreview-1892658645 "Approved")*, *[so-kaushal](https://github.com/scheduleonce/ng-strictify/pull/69#pullrequestreview-1892832104 "Approved")*, *[so-kushal](https://github.com/scheduleonce/ng-strictify/pull/69#pullrequestreview-1892649478 "Approved")*, *[soSkumar](https://github.com/scheduleonce/ng-strictify/pull/69#pullrequestreview-1892582331 "Approved")*, *[vaibhavso](https://github.com/scheduleonce/ng-strictify/pull/69#pullrequestreview-1892609440 "Approved")*

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=scheduleonce%2Fng-strictify).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/scheduleonce/ng-strictify/blob/master/OWNERS)~~ [SO-ashusrivastava,so-kaushal,vaibhavso]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Pull request merged**
