### PR TITLE
[Master] ONCEHUB-51490: updated the change log file and used the ng-strictify version in test-app for fixing the vulnerability

### PR DESCRIPTION
**Pull request by sumitsheokand**
[Master] ONCEHUB-51490: updated the change log file and used the ng-strictify version in test-app for fixing the vulnerability

### CODE REVIEW

**Comment by so-frontend-integrations** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **amanpreetso**
You can assign the PR to them by writing `/assign @amanpreetso` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=scheduleonce%2Fng-strictify).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/scheduleonce/ng-strictify/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Review by ayushbansal-so — APPROVED** [review]

**Comment by so-frontend-integrations** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *[ayushbansal-so](https://github.com/scheduleonce/ng-strictify/pull/38#pullrequestreview-985863626 "Approved")*
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **amanpreetso**
You can assign the PR to them by writing `/assign @amanpreetso` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=scheduleonce%2Fng-strictify).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/scheduleonce/ng-strictify/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Review by SoniRani — APPROVED** [review]

**Review by so-abahadur — APPROVED** [review]

**Comment by so-integrations** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[ayushbansal-so](https://github.com/scheduleonce/ng-strictify/pull/38#pullrequestreview-985863626 "Approved")*, *[so-abahadur](https://github.com/scheduleonce/ng-strictify/pull/38#pullrequestreview-985868543 "Approved")*, *[SoniRani](https://github.com/scheduleonce/ng-strictify/pull/38#pullrequestreview-985868510 "Approved")*

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=scheduleonce%2Fng-strictify).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/scheduleonce/ng-strictify/blob/master/OWNERS)~~ [SoniRani,so-abahadur]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by so-integrations** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[ayushbansal-so](https://github.com/scheduleonce/ng-strictify/pull/38#pullrequestreview-985863626 "Approved")*, *[so-abahadur](https://github.com/scheduleonce/ng-strictify/pull/38#issuecomment-1138274348 "Approved")*, *[SoniRani](https://github.com/scheduleonce/ng-strictify/pull/38#pullrequestreview-985868510 "Approved")*

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=scheduleonce%2Fng-strictify).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/scheduleonce/ng-strictify/blob/master/OWNERS)~~ [SoniRani,so-abahadur]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Pull request merged**
