### PR TITLE
Merging staging-app2 in to master.

### PR DESCRIPTION
**Pull request by ushankar208**

### CODE REVIEW

**Comment by so-frontend-integrations** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **ushankar208**
You can assign the PR to them by writing `/assign @ushankar208` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=scheduleonce%2Fng-strictify).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/scheduleonce/ng-strictify/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Review by vinaykumar01 — APPROVED** [review]

**Comment by so-integrations** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[vinaykumar01](https://github.com/scheduleonce/ng-strictify/pull/52#pullrequestreview-1217010871 "Approved")*

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=scheduleonce%2Fng-strictify).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/scheduleonce/ng-strictify/blob/master/OWNERS)~~ [vinaykumar01]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Review by SO-jagjeetsingh — APPROVED** [review]
Nothing from Stark.

**Comment by oh-frontend** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[SO-jagjeetsingh](https://github.com/scheduleonce/ng-strictify/pull/52#pullrequestreview-1217040290 "Approved")*, *[vinaykumar01](https://github.com/scheduleonce/ng-strictify/pull/52#pullrequestreview-1217010871 "Approved")*

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=scheduleonce%2Fng-strictify).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/scheduleonce/ng-strictify/blob/master/OWNERS)~~ [vinaykumar01]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Review by bharatsinghoh — APPROVED** [review]

**Comment by oh-frontend** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[bharatsinghoh](https://github.com/scheduleonce/ng-strictify/pull/52#pullrequestreview-1217047599 "Approved")*, *[SO-jagjeetsingh](https://github.com/scheduleonce/ng-strictify/pull/52#pullrequestreview-1217040290 "Approved")*, *[vinaykumar01](https://github.com/scheduleonce/ng-strictify/pull/52#pullrequestreview-1217010871 "Approved")*

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=scheduleonce%2Fng-strictify).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/scheduleonce/ng-strictify/blob/master/OWNERS)~~ [vinaykumar01]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Review by ApoorvaSrivastava — APPROVED** [review]
Nothing from Team Graphene

**Comment by oh-frontend** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[ApoorvaSrivastava](https://github.com/scheduleonce/ng-strictify/pull/52#pullrequestreview-1217065144 "Approved")*, *[bharatsinghoh](https://github.com/scheduleonce/ng-strictify/pull/52#pullrequestreview-1217047599 "Approved")*, *[SO-jagjeetsingh](https://github.com/scheduleonce/ng-strictify/pull/52#pullrequestreview-1217040290 "Approved")*, *[vinaykumar01](https://github.com/scheduleonce/ng-strictify/pull/52#pullrequestreview-1217010871 "Approved")*

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=scheduleonce%2Fng-strictify).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/scheduleonce/ng-strictify/blob/master/OWNERS)~~ [vinaykumar01]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Review by vaibhavso — APPROVED** [review]

**Comment by so-frontend-integrations** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[ApoorvaSrivastava](https://github.com/scheduleonce/ng-strictify/pull/52#pullrequestreview-1217065144 "Approved")*, *[bharatsinghoh](https://github.com/scheduleonce/ng-strictify/pull/52#pullrequestreview-1217047599 "Approved")*, *[SO-jagjeetsingh](https://github.com/scheduleonce/ng-strictify/pull/52#pullrequestreview-1217040290 "Approved")*, *[vaibhavso](https://github.com/scheduleonce/ng-strictify/pull/52#pullrequestreview-1217072284 "Approved")*, *[vinaykumar01](https://github.com/scheduleonce/ng-strictify/pull/52#pullrequestreview-1217010871 "Approved")*

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=scheduleonce%2Fng-strictify).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/scheduleonce/ng-strictify/blob/master/OWNERS)~~ [vaibhavso,vinaykumar01]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Review by raghavaggarwalOH — APPROVED** [review]

**Comment by so-frontend-integrations** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[ApoorvaSrivastava](https://github.com/scheduleonce/ng-strictify/pull/52#pullrequestreview-1217065144 "Approved")*, *[bharatsinghoh](https://github.com/scheduleonce/ng-strictify/pull/52#pullrequestreview-1217047599 "Approved")*, *[raghavaggarwalOH](https://github.com/scheduleonce/ng-strictify/pull/52#pullrequestreview-1217079035 "Approved")*, *[SO-jagjeetsingh](https://github.com/scheduleonce/ng-strictify/pull/52#pullrequestreview-1217040290 "Approved")*, *[vaibhavso](https://github.com/scheduleonce/ng-strictify/pull/52#pullrequestreview-1217072284 "Approved")*, *[vinaykumar01](https://github.com/scheduleonce/ng-strictify/pull/52#pullrequestreview-1217010871 "Approved")*

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=scheduleonce%2Fng-strictify).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/scheduleonce/ng-strictify/blob/master/OWNERS)~~ [vaibhavso,vinaykumar01]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Review by amanpreetSO — APPROVED** [review]

**Comment by so-frontend-integrations** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[amanpreetSO](https://github.com/scheduleonce/ng-strictify/pull/52#pullrequestreview-1217084960 "Approved")*, *[ApoorvaSrivastava](https://github.com/scheduleonce/ng-strictify/pull/52#pullrequestreview-1217065144 "Approved")*, *[bharatsinghoh](https://github.com/scheduleonce/ng-strictify/pull/52#pullrequestreview-1217047599 "Approved")*, *[raghavaggarwalOH](https://github.com/scheduleonce/ng-strictify/pull/52#pullrequestreview-1217079035 "Approved")*, *[SO-jagjeetsingh](https://github.com/scheduleonce/ng-strictify/pull/52#pullrequestreview-1217040290 "Approved")*, *[vaibhavso](https://github.com/scheduleonce/ng-strictify/pull/52#pullrequestreview-1217072284 "Approved")*, *[vinaykumar01](https://github.com/scheduleonce/ng-strictify/pull/52#pullrequestreview-1217010871 "Approved")*

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=scheduleonce%2Fng-strictify).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/scheduleonce/ng-strictify/blob/master/OWNERS)~~ [amanpreetSO,vaibhavso,vinaykumar01]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Review by sampada-ojha — APPROVED** [review]

**Comment by so-integrations** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[amanpreetSO](https://github.com/scheduleonce/ng-strictify/pull/52#pullrequestreview-1217084960 "Approved")*, *[ApoorvaSrivastava](https://github.com/scheduleonce/ng-strictify/pull/52#pullrequestreview-1217065144 "Approved")*, *[bharatsinghoh](https://github.com/scheduleonce/ng-strictify/pull/52#pullrequestreview-1217047599 "Approved")*, *[raghavaggarwalOH](https://github.com/scheduleonce/ng-strictify/pull/52#pullrequestreview-1217079035 "Approved")*, *[sampada-ojha](https://github.com/scheduleonce/ng-strictify/pull/52#pullrequestreview-1217103205 "Approved")*, *[SO-jagjeetsingh](https://github.com/scheduleonce/ng-strictify/pull/52#pullrequestreview-1217040290 "Approved")*, *[vaibhavso](https://github.com/scheduleonce/ng-strictify/pull/52#pullrequestreview-1217072284 "Approved")*, *[vinaykumar01](https://github.com/scheduleonce/ng-strictify/pull/52#pullrequestreview-1217010871 "Approved")*

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=scheduleonce%2Fng-strictify).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/scheduleonce/ng-strictify/blob/master/OWNERS)~~ [amanpreetSO,vaibhavso,vinaykumar01]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Review by mohammad-abuzar — APPROVED** [review]

**Comment by so-integrations** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[amanpreetSO](https://github.com/scheduleonce/ng-strictify/pull/52#pullrequestreview-1217084960 "Approved")*, *[ApoorvaSrivastava](https://github.com/scheduleonce/ng-strictify/pull/52#pullrequestreview-1217065144 "Approved")*, *[bharatsinghoh](https://github.com/scheduleonce/ng-strictify/pull/52#pullrequestreview-1217047599 "Approved")*, *[mohammad-abuzar](https://github.com/scheduleonce/ng-strictify/pull/52#pullrequestreview-1217111021 "Approved")*, *[raghavaggarwalOH](https://github.com/scheduleonce/ng-strictify/pull/52#pullrequestreview-1217079035 "Approved")*, *[sampada-ojha](https://github.com/scheduleonce/ng-strictify/pull/52#pullrequestreview-1217103205 "Approved")*, *[SO-jagjeetsingh](https://github.com/scheduleonce/ng-strictify/pull/52#pullrequestreview-1217040290 "Approved")*, *[vaibhavso](https://github.com/scheduleonce/ng-strictify/pull/52#pullrequestreview-1217072284 "Approved")*, *[vinaykumar01](https://github.com/scheduleonce/ng-strictify/pull/52#pullrequestreview-1217010871 "Approved")*

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=scheduleonce%2Fng-strictify).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/scheduleonce/ng-strictify/blob/master/OWNERS)~~ [amanpreetSO,vaibhavso,vinaykumar01]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Review by rameshwarverma — APPROVED** [review]

**Review by oh-rahulsingla — APPROVED** [review]

**Comment by so-integrations** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[amanpreetSO](https://github.com/scheduleonce/ng-strictify/pull/52#pullrequestreview-1217084960 "Approved")*, *[ApoorvaSrivastava](https://github.com/scheduleonce/ng-strictify/pull/52#pullrequestreview-1217065144 "Approved")*, *[bharatsinghoh](https://github.com/scheduleonce/ng-strictify/pull/52#pullrequestreview-1217047599 "Approved")*, *[mohammad-abuzar](https://github.com/scheduleonce/ng-strictify/pull/52#pullrequestreview-1217111021 "Approved")*, *[oh-rahulsingla](https://github.com/scheduleonce/ng-strictify/pull/52#pullrequestreview-1217121214 "Approved")*, *[raghavaggarwalOH](https://github.com/scheduleonce/ng-strictify/pull/52#pullrequestreview-1217079035 "Approved")*, *[rameshwarverma](https://github.com/scheduleonce/ng-strictify/pull/52#pullrequestreview-1217111316 "Approved")*, *[sampada-ojha](https://github.com/scheduleonce/ng-strictify/pull/52#pullrequestreview-1217103205 "Approved")*, *[SO-jagjeetsingh](https://github.com/scheduleonce/ng-strictify/pull/52#pullrequestreview-1217040290 "Approved")*, *[vaibhavso](https://github.com/scheduleonce/ng-strictify/pull/52#pullrequestreview-1217072284 "Approved")*, *[vinaykumar01](https://github.com/scheduleonce/ng-strictify/pull/52#pullrequestreview-1217010871 "Approved")*

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=scheduleonce%2Fng-strictify).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/scheduleonce/ng-strictify/blob/master/OWNERS)~~ [amanpreetSO,vaibhavso,vinaykumar01]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Review by AmitPandeyScheduleonce — APPROVED** [review]

**Comment by oh-frontend** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[amanpreetSO](https://github.com/scheduleonce/ng-strictify/pull/52#pullrequestreview-1217084960 "Approved")*, *[AmitPandeyScheduleonce](https://github.com/scheduleonce/ng-strictify/pull/52#pullrequestreview-1217143549 "Approved")*, *[ApoorvaSrivastava](https://github.com/scheduleonce/ng-strictify/pull/52#pullrequestreview-1217065144 "Approved")*, *[bharatsinghoh](https://github.com/scheduleonce/ng-strictify/pull/52#pullrequestreview-1217047599 "Approved")*, *[mohammad-abuzar](https://github.com/scheduleonce/ng-strictify/pull/52#pullrequestreview-1217111021 "Approved")*, *[oh-rahulsingla](https://github.com/scheduleonce/ng-strictify/pull/52#pullrequestreview-1217121214 "Approved")*, *[raghavaggarwalOH](https://github.com/scheduleonce/ng-strictify/pull/52#pullrequestreview-1217079035 "Approved")*, *[rameshwarverma](https://github.com/scheduleonce/ng-strictify/pull/52#pullrequestreview-1217111316 "Approved")*, *[sampada-ojha](https://github.com/scheduleonce/ng-strictify/pull/52#pullrequestreview-1217103205 "Approved")*, *[SO-jagjeetsingh](https://github.com/scheduleonce/ng-strictify/pull/52#pullrequestreview-1217040290 "Approved")*, *[vaibhavso](https://github.com/scheduleonce/ng-strictify/pull/52#pullrequestreview-1217072284 "Approved")*, *[vinaykumar01](https://github.com/scheduleonce/ng-strictify/pull/52#pullrequestreview-1217010871 "Approved")*

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=scheduleonce%2Fng-strictify).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/scheduleonce/ng-strictify/blob/master/OWNERS)~~ [AmitPandeyScheduleonce,amanpreetSO,vaibhavso,vinaykumar01]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by oh-frontend** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[amanpreetSO](https://github.com/scheduleonce/ng-strictify/pull/52#pullrequestreview-1217084960 "Approved")*, *[AmitPandeyScheduleonce](https://github.com/scheduleonce/ng-strictify/pull/52#pullrequestreview-1217143549 "Approved")*, *[ApoorvaSrivastava](https://github.com/scheduleonce/ng-strictify/pull/52#pullrequestreview-1217065144 "Approved")*, *[bharatsinghoh](https://github.com/scheduleonce/ng-strictify/pull/52#pullrequestreview-1217047599 "Approved")*, *[mohammad-abuzar](https://github.com/scheduleonce/ng-strictify/pull/52#pullrequestreview-1217111021 "Approved")*, *[oh-rahulsingla](https://github.com/scheduleonce/ng-strictify/pull/52#pullrequestreview-1217121214 "Approved")*, *[raghavaggarwalOH](https://github.com/scheduleonce/ng-strictify/pull/52#pullrequestreview-1217079035 "Approved")*, *[rameshwarverma](https://github.com/scheduleonce/ng-strictify/pull/52#pullrequestreview-1217111316 "Approved")*, *[sampada-ojha](https://github.com/scheduleonce/ng-strictify/pull/52#pullrequestreview-1217103205 "Approved")*, *[SO-jagjeetsingh](https://github.com/scheduleonce/ng-strictify/pull/52#pullrequestreview-1217040290 "Approved")*, *[sohimanshu](https://github.com/scheduleonce/ng-strictify/pull/52#issuecomment-1350793605 "Approved")*, *[vaibhavso](https://github.com/scheduleonce/ng-strictify/pull/52#pullrequestreview-1217072284 "Approved")*, *[vinaykumar01](https://github.com/scheduleonce/ng-strictify/pull/52#pullrequestreview-1217010871 "Approved")*

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=scheduleonce%2Fng-strictify).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/scheduleonce/ng-strictify/blob/master/OWNERS)~~ [AmitPandeyScheduleonce,amanpreetSO,sohimanshu,vaibhavso,vinaykumar01]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by so-frontend-integrations** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[amanpreetSO](https://github.com/scheduleonce/ng-strictify/pull/52#pullrequestreview-1217084960 "Approved")*, *[AmitPandeyScheduleonce](https://github.com/scheduleonce/ng-strictify/pull/52#pullrequestreview-1217143549 "Approved")*, *[ApoorvaSrivastava](https://github.com/scheduleonce/ng-strictify/pull/52#pullrequestreview-1217065144 "Approved")*, *[bharatsinghoh](https://github.com/scheduleonce/ng-strictify/pull/52#pullrequestreview-1217047599 "Approved")*, *[mohammad-abuzar](https://github.com/scheduleonce/ng-strictify/pull/52#pullrequestreview-1217111021 "Approved")*, *[oh-rahulsingla](https://github.com/scheduleonce/ng-strictify/pull/52#pullrequestreview-1217121214 "Approved")*, *[raghavaggarwalOH](https://github.com/scheduleonce/ng-strictify/pull/52#pullrequestreview-1217079035 "Approved")*, *[rameshwarverma](https://github.com/scheduleonce/ng-strictify/pull/52#pullrequestreview-1217111316 "Approved")*, *[sampada-ojha](https://github.com/scheduleonce/ng-strictify/pull/52#pullrequestreview-1217103205 "Approved")*, *[SO-jagjeetsingh](https://github.com/scheduleonce/ng-strictify/pull/52#pullrequestreview-1217040290 "Approved")*, *[sohimanshu](https://github.com/scheduleonce/ng-strictify/pull/52#issuecomment-1350793605 "Approved")*, *[vaibhavso](https://github.com/scheduleonce/ng-strictify/pull/52#pullrequestreview-1217072284 "Approved")*, *[vinaykumar01](https://github.com/scheduleonce/ng-strictify/pull/52#pullrequestreview-1217010871 "Approved")*

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=scheduleonce%2Fng-strictify).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/scheduleonce/ng-strictify/blob/master/OWNERS)~~ [AmitPandeyScheduleonce,amanpreetSO,sohimanshu,vaibhavso,vinaykumar01]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Pull request merged**
