### PR TITLE
Merging staging-app2 in to master.

### PR DESCRIPTION
**Pull request by ushankar208**

### CODE REVIEW

**Comment by oh-frontend** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **ushankar208**
You can assign the PR to them by writing `/assign @ushankar208` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=scheduleonce%2Fng-strictify).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/scheduleonce/ng-strictify/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Review by so-kushal — APPROVED** [review]

**Comment by so-frontend-integrations** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *[so-kushal](https://github.com/scheduleonce/ng-strictify/pull/43#pullrequestreview-1123342825 "Approved")*
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **ushankar208**
You can assign the PR to them by writing `/assign @ushankar208` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=scheduleonce%2Fng-strictify).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/scheduleonce/ng-strictify/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Review by raghavaggarwalOH — APPROVED** [review]

**Comment by so-frontend-integrations** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *[raghavaggarwalOH](https://github.com/scheduleonce/ng-strictify/pull/43#pullrequestreview-1123350793 "Approved")*, *[so-kushal](https://github.com/scheduleonce/ng-strictify/pull/43#pullrequestreview-1123342825 "Approved")*
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **ushankar208**
You can assign the PR to them by writing `/assign @ushankar208` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=scheduleonce%2Fng-strictify).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/scheduleonce/ng-strictify/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Review by raghavaggarwalOH — APPROVED** [review]

**Comment by so-frontend-integrations** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *[raghavaggarwalOH](https://github.com/scheduleonce/ng-strictify/pull/43#pullrequestreview-1123352005 "Approved")*, *[so-kushal](https://github.com/scheduleonce/ng-strictify/pull/43#pullrequestreview-1123342825 "Approved")*
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **ushankar208**
You can assign the PR to them by writing `/assign @ushankar208` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=scheduleonce%2Fng-strictify).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/scheduleonce/ng-strictify/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Review by ApoorvaSrivastava — APPROVED** [review]
Nothing from Team Graphene

**Review by vaibhavso — APPROVED** [review]

**Comment by so-frontend-integrations** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[ApoorvaSrivastava](https://github.com/scheduleonce/ng-strictify/pull/43#pullrequestreview-1123357214 "Approved")*, *[raghavaggarwalOH](https://github.com/scheduleonce/ng-strictify/pull/43#pullrequestreview-1123352005 "Approved")*, *[so-kushal](https://github.com/scheduleonce/ng-strictify/pull/43#pullrequestreview-1123342825 "Approved")*, *[vaibhavso](https://github.com/scheduleonce/ng-strictify/pull/43#pullrequestreview-1123357319 "Approved")*

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=scheduleonce%2Fng-strictify).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/scheduleonce/ng-strictify/blob/master/OWNERS)~~ [vaibhavso]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by so-frontend-integrations** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[ApoorvaSrivastava](https://github.com/scheduleonce/ng-strictify/pull/43#pullrequestreview-1123357214 "Approved")*, *[raghavaggarwalOH](https://github.com/scheduleonce/ng-strictify/pull/43#pullrequestreview-1123352005 "Approved")*, *[so-kushal](https://github.com/scheduleonce/ng-strictify/pull/43#pullrequestreview-1123342825 "Approved")*, *[vaibhavso](https://github.com/scheduleonce/ng-strictify/pull/43#pullrequestreview-1123357319 "Approved")*

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=scheduleonce%2Fng-strictify).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/scheduleonce/ng-strictify/blob/master/OWNERS)~~ [vaibhavso]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by so-frontend-integrations** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[ApoorvaSrivastava](https://github.com/scheduleonce/ng-strictify/pull/43#pullrequestreview-1123357214 "Approved")*, *[raghavaggarwalOH](https://github.com/scheduleonce/ng-strictify/pull/43#pullrequestreview-1123352005 "Approved")*, *[so-kushal](https://github.com/scheduleonce/ng-strictify/pull/43#pullrequestreview-1123342825 "Approved")*, *[vaibhavso](https://github.com/scheduleonce/ng-strictify/pull/43#pullrequestreview-1123357319 "Approved")*

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=scheduleonce%2Fng-strictify).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/scheduleonce/ng-strictify/blob/master/OWNERS)~~ [vaibhavso]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Review by SO-ashusrivastava — APPROVED** [review]

**Comment by so-frontend-integrations** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[ApoorvaSrivastava](https://github.com/scheduleonce/ng-strictify/pull/43#pullrequestreview-1123357214 "Approved")*, *[raghavaggarwalOH](https://github.com/scheduleonce/ng-strictify/pull/43#pullrequestreview-1123352005 "Approved")*, *[SO-ashusrivastava](https://github.com/scheduleonce/ng-strictify/pull/43#pullrequestreview-1123358293 "Approved")*, *[so-kushal](https://github.com/scheduleonce/ng-strictify/pull/43#pullrequestreview-1123342825 "Approved")*, *[vaibhavso](https://github.com/scheduleonce/ng-strictify/pull/43#pullrequestreview-1123357319 "Approved")*

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=scheduleonce%2Fng-strictify).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/scheduleonce/ng-strictify/blob/master/OWNERS)~~ [SO-ashusrivastava,vaibhavso]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Review by oh-rahulsingla — APPROVED** [review]

**Comment by so-integrations** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[ApoorvaSrivastava](https://github.com/scheduleonce/ng-strictify/pull/43#pullrequestreview-1123357214 "Approved")*, *[oh-rahulsingla](https://github.com/scheduleonce/ng-strictify/pull/43#pullrequestreview-1123380608 "Approved")*, *[raghavaggarwalOH](https://github.com/scheduleonce/ng-strictify/pull/43#pullrequestreview-1123352005 "Approved")*, *[SO-ashusrivastava](https://github.com/scheduleonce/ng-strictify/pull/43#pullrequestreview-1123358293 "Approved")*, *[so-kushal](https://github.com/scheduleonce/ng-strictify/pull/43#pullrequestreview-1123342825 "Approved")*, *[vaibhavso](https://github.com/scheduleonce/ng-strictify/pull/43#pullrequestreview-1123357319 "Approved")*

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=scheduleonce%2Fng-strictify).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/scheduleonce/ng-strictify/blob/master/OWNERS)~~ [SO-ashusrivastava,vaibhavso]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Review by rameshwarverma — APPROVED** [review]

**Comment by so-integrations** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[ApoorvaSrivastava](https://github.com/scheduleonce/ng-strictify/pull/43#pullrequestreview-1123357214 "Approved")*, *[oh-rahulsingla](https://github.com/scheduleonce/ng-strictify/pull/43#pullrequestreview-1123380608 "Approved")*, *[raghavaggarwalOH](https://github.com/scheduleonce/ng-strictify/pull/43#pullrequestreview-1123352005 "Approved")*, *[rameshwarverma](https://github.com/scheduleonce/ng-strictify/pull/43#pullrequestreview-1123382491 "Approved")*, *[SO-ashusrivastava](https://github.com/scheduleonce/ng-strictify/pull/43#pullrequestreview-1123358293 "Approved")*, *[so-kushal](https://github.com/scheduleonce/ng-strictify/pull/43#pullrequestreview-1123342825 "Approved")*, *[vaibhavso](https://github.com/scheduleonce/ng-strictify/pull/43#pullrequestreview-1123357319 "Approved")*

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=scheduleonce%2Fng-strictify).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/scheduleonce/ng-strictify/blob/master/OWNERS)~~ [SO-ashusrivastava,vaibhavso]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Review by bharatsinghoh — APPROVED** [review]

**Comment by so-integrations** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[ApoorvaSrivastava](https://github.com/scheduleonce/ng-strictify/pull/43#pullrequestreview-1123357214 "Approved")*, *[bharatsinghoh](https://github.com/scheduleonce/ng-strictify/pull/43#pullrequestreview-1123383055 "Approved")*, *[oh-rahulsingla](https://github.com/scheduleonce/ng-strictify/pull/43#pullrequestreview-1123380608 "Approved")*, *[raghavaggarwalOH](https://github.com/scheduleonce/ng-strictify/pull/43#pullrequestreview-1123352005 "Approved")*, *[rameshwarverma](https://github.com/scheduleonce/ng-strictify/pull/43#pullrequestreview-1123382491 "Approved")*, *[SO-ashusrivastava](https://github.com/scheduleonce/ng-strictify/pull/43#pullrequestreview-1123358293 "Approved")*, *[so-kushal](https://github.com/scheduleonce/ng-strictify/pull/43#pullrequestreview-1123342825 "Approved")*, *[vaibhavso](https://github.com/scheduleonce/ng-strictify/pull/43#pullrequestreview-1123357319 "Approved")*

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=scheduleonce%2Fng-strictify).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/scheduleonce/ng-strictify/blob/master/OWNERS)~~ [SO-ashusrivastava,vaibhavso]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Review by SO-jagjeetsingh — APPROVED** [review]
Nothing from Stark

**Comment by so-integrations** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[ApoorvaSrivastava](https://github.com/scheduleonce/ng-strictify/pull/43#pullrequestreview-1123357214 "Approved")*, *[bharatsinghoh](https://github.com/scheduleonce/ng-strictify/pull/43#pullrequestreview-1123383055 "Approved")*, *[oh-rahulsingla](https://github.com/scheduleonce/ng-strictify/pull/43#pullrequestreview-1123380608 "Approved")*, *[raghavaggarwalOH](https://github.com/scheduleonce/ng-strictify/pull/43#pullrequestreview-1123352005 "Approved")*, *[rameshwarverma](https://github.com/scheduleonce/ng-strictify/pull/43#pullrequestreview-1123382491 "Approved")*, *[SO-ashusrivastava](https://github.com/scheduleonce/ng-strictify/pull/43#pullrequestreview-1123358293 "Approved")*, *[SO-jagjeetsingh](https://github.com/scheduleonce/ng-strictify/pull/43#pullrequestreview-1123388271 "Approved")*, *[so-kushal](https://github.com/scheduleonce/ng-strictify/pull/43#pullrequestreview-1123342825 "Approved")*, *[vaibhavso](https://github.com/scheduleonce/ng-strictify/pull/43#pullrequestreview-1123357319 "Approved")*

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=scheduleonce%2Fng-strictify).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/scheduleonce/ng-strictify/blob/master/OWNERS)~~ [SO-ashusrivastava,vaibhavso]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Review by nrathour — APPROVED** [review]

**Comment by so-integrations** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[ApoorvaSrivastava](https://github.com/scheduleonce/ng-strictify/pull/43#pullrequestreview-1123357214 "Approved")*, *[bharatsinghoh](https://github.com/scheduleonce/ng-strictify/pull/43#pullrequestreview-1123383055 "Approved")*, *[nrathour](https://github.com/scheduleonce/ng-strictify/pull/43#pullrequestreview-1123390714 "Approved")*, *[oh-rahulsingla](https://github.com/scheduleonce/ng-strictify/pull/43#pullrequestreview-1123380608 "Approved")*, *[raghavaggarwalOH](https://github.com/scheduleonce/ng-strictify/pull/43#pullrequestreview-1123352005 "Approved")*, *[rameshwarverma](https://github.com/scheduleonce/ng-strictify/pull/43#pullrequestreview-1123382491 "Approved")*, *[SO-ashusrivastava](https://github.com/scheduleonce/ng-strictify/pull/43#pullrequestreview-1123358293 "Approved")*, *[SO-jagjeetsingh](https://github.com/scheduleonce/ng-strictify/pull/43#pullrequestreview-1123388271 "Approved")*, *[so-kushal](https://github.com/scheduleonce/ng-strictify/pull/43#pullrequestreview-1123342825 "Approved")*, *[vaibhavso](https://github.com/scheduleonce/ng-strictify/pull/43#pullrequestreview-1123357319 "Approved")*

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=scheduleonce%2Fng-strictify).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/scheduleonce/ng-strictify/blob/master/OWNERS)~~ [SO-ashusrivastava,vaibhavso]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Review by sampada-ojha — APPROVED** [review]

**Comment by oh-frontend** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[ApoorvaSrivastava](https://github.com/scheduleonce/ng-strictify/pull/43#pullrequestreview-1123357214 "Approved")*, *[bharatsinghoh](https://github.com/scheduleonce/ng-strictify/pull/43#pullrequestreview-1123383055 "Approved")*, *[nrathour](https://github.com/scheduleonce/ng-strictify/pull/43#pullrequestreview-1123390714 "Approved")*, *[oh-rahulsingla](https://github.com/scheduleonce/ng-strictify/pull/43#pullrequestreview-1123380608 "Approved")*, *[raghavaggarwalOH](https://github.com/scheduleonce/ng-strictify/pull/43#pullrequestreview-1123352005 "Approved")*, *[rameshwarverma](https://github.com/scheduleonce/ng-strictify/pull/43#pullrequestreview-1123382491 "Approved")*, *[sampada-ojha](https://github.com/scheduleonce/ng-strictify/pull/43#pullrequestreview-1123409226 "Approved")*, *[SO-ashusrivastava](https://github.com/scheduleonce/ng-strictify/pull/43#pullrequestreview-1123358293 "Approved")*, *[SO-jagjeetsingh](https://github.com/scheduleonce/ng-strictify/pull/43#pullrequestreview-1123388271 "Approved")*, *[so-kushal](https://github.com/scheduleonce/ng-strictify/pull/43#pullrequestreview-1123342825 "Approved")*, *[vaibhavso](https://github.com/scheduleonce/ng-strictify/pull/43#pullrequestreview-1123357319 "Approved")*

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=scheduleonce%2Fng-strictify).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/scheduleonce/ng-strictify/blob/master/OWNERS)~~ [SO-ashusrivastava,vaibhavso]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Review by vinaykumar01 — APPROVED** [review]

**Comment by so-frontend-integrations** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[ApoorvaSrivastava](https://github.com/scheduleonce/ng-strictify/pull/43#pullrequestreview-1123357214 "Approved")*, *[bharatsinghoh](https://github.com/scheduleonce/ng-strictify/pull/43#pullrequestreview-1123383055 "Approved")*, *[nrathour](https://github.com/scheduleonce/ng-strictify/pull/43#pullrequestreview-1123390714 "Approved")*, *[oh-rahulsingla](https://github.com/scheduleonce/ng-strictify/pull/43#pullrequestreview-1123380608 "Approved")*, *[raghavaggarwalOH](https://github.com/scheduleonce/ng-strictify/pull/43#pullrequestreview-1123352005 "Approved")*, *[rameshwarverma](https://github.com/scheduleonce/ng-strictify/pull/43#pullrequestreview-1123382491 "Approved")*, *[sampada-ojha](https://github.com/scheduleonce/ng-strictify/pull/43#pullrequestreview-1123409226 "Approved")*, *[SO-ashusrivastava](https://github.com/scheduleonce/ng-strictify/pull/43#pullrequestreview-1123358293 "Approved")*, *[SO-jagjeetsingh](https://github.com/scheduleonce/ng-strictify/pull/43#pullrequestreview-1123388271 "Approved")*, *[so-kushal](https://github.com/scheduleonce/ng-strictify/pull/43#pullrequestreview-1123342825 "Approved")*, *[vaibhavso](https://github.com/scheduleonce/ng-strictify/pull/43#pullrequestreview-1123357319 "Approved")*, *[vinaykumar01](https://github.com/scheduleonce/ng-strictify/pull/43#pullrequestreview-1123437447 "Approved")*

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=scheduleonce%2Fng-strictify).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/scheduleonce/ng-strictify/blob/master/OWNERS)~~ [SO-ashusrivastava,vaibhavso,vinaykumar01]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by oh-frontend** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[ApoorvaSrivastava](https://github.com/scheduleonce/ng-strictify/pull/43#pullrequestreview-1123357214 "Approved")*, *[bharatsinghoh](https://github.com/scheduleonce/ng-strictify/pull/43#pullrequestreview-1123383055 "Approved")*, *[nrathour](https://github.com/scheduleonce/ng-strictify/pull/43#pullrequestreview-1123390714 "Approved")*, *[oh-rahulsingla](https://github.com/scheduleonce/ng-strictify/pull/43#pullrequestreview-1123380608 "Approved")*, *[raghavaggarwalOH](https://github.com/scheduleonce/ng-strictify/pull/43#pullrequestreview-1123352005 "Approved")*, *[rameshwarverma](https://github.com/scheduleonce/ng-strictify/pull/43#pullrequestreview-1123382491 "Approved")*, *[sampada-ojha](https://github.com/scheduleonce/ng-strictify/pull/43#pullrequestreview-1123409226 "Approved")*, *[Shalini-Nagmoti](https://github.com/scheduleonce/ng-strictify/pull/43#issuecomment-1260746320 "Approved")*, *[SO-ashusrivastava](https://github.com/scheduleonce/ng-strictify/pull/43#pullrequestreview-1123358293 "Approved")*, *[SO-jagjeetsingh](https://github.com/scheduleonce/ng-strictify/pull/43#pullrequestreview-1123388271 "Approved")*, *[so-kushal](https://github.com/scheduleonce/ng-strictify/pull/43#pullrequestreview-1123342825 "Approved")*, *[vaibhavso](https://github.com/scheduleonce/ng-strictify/pull/43#pullrequestreview-1123357319 "Approved")*, *[vinaykumar01](https://github.com/scheduleonce/ng-strictify/pull/43#pullrequestreview-1123437447 "Approved")*

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=scheduleonce%2Fng-strictify).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/scheduleonce/ng-strictify/blob/master/OWNERS)~~ [SO-ashusrivastava,vaibhavso,vinaykumar01]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Pull request merged**
