### PR TITLE
Merging staging-app2 in to master.

### PR DESCRIPTION
**Pull request by ushankar208**

### CODE REVIEW

**Comment by oh-frontend** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **ushankar208**
You can assign the PR to them by writing `/assign @ushankar208` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=scheduleonce%2Fng-strictify).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/scheduleonce/ng-strictify/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Review by so-kushal — APPROVED** [review]

**Comment by so-frontend-integrations** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *[so-kushal](https://github.com/scheduleonce/ng-strictify/pull/49#pullrequestreview-1198900993 "Approved")*
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **ushankar208**
You can assign the PR to them by writing `/assign @ushankar208` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=scheduleonce%2Fng-strictify).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/scheduleonce/ng-strictify/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Review by vinaykumar01 — APPROVED** [review]

**Comment by so-frontend-integrations** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[so-kushal](https://github.com/scheduleonce/ng-strictify/pull/49#pullrequestreview-1198900993 "Approved")*, *[vinaykumar01](https://github.com/scheduleonce/ng-strictify/pull/49#pullrequestreview-1198912162 "Approved")*

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=scheduleonce%2Fng-strictify).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/scheduleonce/ng-strictify/blob/master/OWNERS)~~ [vinaykumar01]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by so-frontend-integrations** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[so-kushal](https://github.com/scheduleonce/ng-strictify/pull/49#pullrequestreview-1198900993 "Approved")*, *[vinaykumar01](https://github.com/scheduleonce/ng-strictify/pull/49#pullrequestreview-1198912162 "Approved")*

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=scheduleonce%2Fng-strictify).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/scheduleonce/ng-strictify/blob/master/OWNERS)~~ [vinaykumar01]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Review by SO-jagjeetsingh — APPROVED** [review]
Nothing from Stark

**Comment by so-integrations** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[SO-jagjeetsingh](https://github.com/scheduleonce/ng-strictify/pull/49#pullrequestreview-1198946135 "Approved")*, *[so-kushal](https://github.com/scheduleonce/ng-strictify/pull/49#pullrequestreview-1198900993 "Approved")*, *[vinaykumar01](https://github.com/scheduleonce/ng-strictify/pull/49#pullrequestreview-1198912162 "Approved")*

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=scheduleonce%2Fng-strictify).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/scheduleonce/ng-strictify/blob/master/OWNERS)~~ [vinaykumar01]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Review by raghavaggarwalOH — APPROVED** [review]

**Comment by oh-frontend** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[raghavaggarwalOH](https://github.com/scheduleonce/ng-strictify/pull/49#pullrequestreview-1198963497 "Approved")*, *[SO-jagjeetsingh](https://github.com/scheduleonce/ng-strictify/pull/49#pullrequestreview-1198946135 "Approved")*, *[so-kushal](https://github.com/scheduleonce/ng-strictify/pull/49#pullrequestreview-1198900993 "Approved")*, *[vinaykumar01](https://github.com/scheduleonce/ng-strictify/pull/49#pullrequestreview-1198912162 "Approved")*

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=scheduleonce%2Fng-strictify).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/scheduleonce/ng-strictify/blob/master/OWNERS)~~ [vinaykumar01]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Review by SO-ashusrivastava — APPROVED** [review]

**Comment by oh-frontend** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[raghavaggarwalOH](https://github.com/scheduleonce/ng-strictify/pull/49#pullrequestreview-1198963497 "Approved")*, *[SO-ashusrivastava](https://github.com/scheduleonce/ng-strictify/pull/49#pullrequestreview-1198977583 "Approved")*, *[SO-jagjeetsingh](https://github.com/scheduleonce/ng-strictify/pull/49#pullrequestreview-1198946135 "Approved")*, *[so-kushal](https://github.com/scheduleonce/ng-strictify/pull/49#pullrequestreview-1198900993 "Approved")*, *[vinaykumar01](https://github.com/scheduleonce/ng-strictify/pull/49#pullrequestreview-1198912162 "Approved")*

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=scheduleonce%2Fng-strictify).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/scheduleonce/ng-strictify/blob/master/OWNERS)~~ [SO-ashusrivastava,vinaykumar01]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Review by vaibhavso — APPROVED** [review]

**Comment by oh-frontend** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[raghavaggarwalOH](https://github.com/scheduleonce/ng-strictify/pull/49#pullrequestreview-1198963497 "Approved")*, *[SO-ashusrivastava](https://github.com/scheduleonce/ng-strictify/pull/49#pullrequestreview-1198977583 "Approved")*, *[SO-jagjeetsingh](https://github.com/scheduleonce/ng-strictify/pull/49#pullrequestreview-1198946135 "Approved")*, *[so-kushal](https://github.com/scheduleonce/ng-strictify/pull/49#pullrequestreview-1198900993 "Approved")*, *[vaibhavso](https://github.com/scheduleonce/ng-strictify/pull/49#pullrequestreview-1198986520 "Approved")*, *[vinaykumar01](https://github.com/scheduleonce/ng-strictify/pull/49#pullrequestreview-1198912162 "Approved")*

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=scheduleonce%2Fng-strictify).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/scheduleonce/ng-strictify/blob/master/OWNERS)~~ [SO-ashusrivastava,vaibhavso,vinaykumar01]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Review by sampada-ojha — APPROVED** [review]

**Comment by so-frontend-integrations** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[raghavaggarwalOH](https://github.com/scheduleonce/ng-strictify/pull/49#pullrequestreview-1198963497 "Approved")*, *[sampada-ojha](https://github.com/scheduleonce/ng-strictify/pull/49#pullrequestreview-1198997983 "Approved")*, *[SO-ashusrivastava](https://github.com/scheduleonce/ng-strictify/pull/49#pullrequestreview-1198977583 "Approved")*, *[SO-jagjeetsingh](https://github.com/scheduleonce/ng-strictify/pull/49#pullrequestreview-1198946135 "Approved")*, *[so-kushal](https://github.com/scheduleonce/ng-strictify/pull/49#pullrequestreview-1198900993 "Approved")*, *[vaibhavso](https://github.com/scheduleonce/ng-strictify/pull/49#pullrequestreview-1198986520 "Approved")*, *[vinaykumar01](https://github.com/scheduleonce/ng-strictify/pull/49#pullrequestreview-1198912162 "Approved")*

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=scheduleonce%2Fng-strictify).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/scheduleonce/ng-strictify/blob/master/OWNERS)~~ [SO-ashusrivastava,vaibhavso,vinaykumar01]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Review by rameshwarverma — APPROVED** [review]

**Comment by so-frontend-integrations** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[raghavaggarwalOH](https://github.com/scheduleonce/ng-strictify/pull/49#pullrequestreview-1198963497 "Approved")*, *[rameshwarverma](https://github.com/scheduleonce/ng-strictify/pull/49#pullrequestreview-1199018989 "Approved")*, *[sampada-ojha](https://github.com/scheduleonce/ng-strictify/pull/49#pullrequestreview-1198997983 "Approved")*, *[SO-ashusrivastava](https://github.com/scheduleonce/ng-strictify/pull/49#pullrequestreview-1198977583 "Approved")*, *[SO-jagjeetsingh](https://github.com/scheduleonce/ng-strictify/pull/49#pullrequestreview-1198946135 "Approved")*, *[so-kushal](https://github.com/scheduleonce/ng-strictify/pull/49#pullrequestreview-1198900993 "Approved")*, *[vaibhavso](https://github.com/scheduleonce/ng-strictify/pull/49#pullrequestreview-1198986520 "Approved")*, *[vinaykumar01](https://github.com/scheduleonce/ng-strictify/pull/49#pullrequestreview-1198912162 "Approved")*

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=scheduleonce%2Fng-strictify).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/scheduleonce/ng-strictify/blob/master/OWNERS)~~ [SO-ashusrivastava,vaibhavso,vinaykumar01]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Review by so-ravindra — APPROVED** [review]

**Comment by so-integrations** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[raghavaggarwalOH](https://github.com/scheduleonce/ng-strictify/pull/49#pullrequestreview-1198963497 "Approved")*, *[rameshwarverma](https://github.com/scheduleonce/ng-strictify/pull/49#pullrequestreview-1199018989 "Approved")*, *[sampada-ojha](https://github.com/scheduleonce/ng-strictify/pull/49#pullrequestreview-1198997983 "Approved")*, *[SO-ashusrivastava](https://github.com/scheduleonce/ng-strictify/pull/49#pullrequestreview-1198977583 "Approved")*, *[SO-jagjeetsingh](https://github.com/scheduleonce/ng-strictify/pull/49#pullrequestreview-1198946135 "Approved")*, *[so-kushal](https://github.com/scheduleonce/ng-strictify/pull/49#pullrequestreview-1198900993 "Approved")*, *[so-ravindra](https://github.com/scheduleonce/ng-strictify/pull/49#pullrequestreview-1199040294 "Approved")*, *[vaibhavso](https://github.com/scheduleonce/ng-strictify/pull/49#pullrequestreview-1198986520 "Approved")*, *[vinaykumar01](https://github.com/scheduleonce/ng-strictify/pull/49#pullrequestreview-1198912162 "Approved")*

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=scheduleonce%2Fng-strictify).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/scheduleonce/ng-strictify/blob/master/OWNERS)~~ [SO-ashusrivastava,vaibhavso,vinaykumar01]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Review by oh-rahulsingla — APPROVED** [review]

**Comment by oh-frontend** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[oh-rahulsingla](https://github.com/scheduleonce/ng-strictify/pull/49#pullrequestreview-1199067515 "Approved")*, *[raghavaggarwalOH](https://github.com/scheduleonce/ng-strictify/pull/49#pullrequestreview-1198963497 "Approved")*, *[rameshwarverma](https://github.com/scheduleonce/ng-strictify/pull/49#pullrequestreview-1199018989 "Approved")*, *[sampada-ojha](https://github.com/scheduleonce/ng-strictify/pull/49#pullrequestreview-1198997983 "Approved")*, *[SO-ashusrivastava](https://github.com/scheduleonce/ng-strictify/pull/49#pullrequestreview-1198977583 "Approved")*, *[SO-jagjeetsingh](https://github.com/scheduleonce/ng-strictify/pull/49#pullrequestreview-1198946135 "Approved")*, *[so-kushal](https://github.com/scheduleonce/ng-strictify/pull/49#pullrequestreview-1198900993 "Approved")*, *[so-ravindra](https://github.com/scheduleonce/ng-strictify/pull/49#pullrequestreview-1199040294 "Approved")*, *[vaibhavso](https://github.com/scheduleonce/ng-strictify/pull/49#pullrequestreview-1198986520 "Approved")*, *[vinaykumar01](https://github.com/scheduleonce/ng-strictify/pull/49#pullrequestreview-1198912162 "Approved")*

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=scheduleonce%2Fng-strictify).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/scheduleonce/ng-strictify/blob/master/OWNERS)~~ [SO-ashusrivastava,vaibhavso,vinaykumar01]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Review by oh-damini — APPROVED** [review]

**Comment by so-integrations** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[oh-damini](https://github.com/scheduleonce/ng-strictify/pull/49#pullrequestreview-1199116695 "Approved")*, *[oh-rahulsingla](https://github.com/scheduleonce/ng-strictify/pull/49#pullrequestreview-1199067515 "Approved")*, *[raghavaggarwalOH](https://github.com/scheduleonce/ng-strictify/pull/49#pullrequestreview-1198963497 "Approved")*, *[rameshwarverma](https://github.com/scheduleonce/ng-strictify/pull/49#pullrequestreview-1199018989 "Approved")*, *[sampada-ojha](https://github.com/scheduleonce/ng-strictify/pull/49#pullrequestreview-1198997983 "Approved")*, *[SO-ashusrivastava](https://github.com/scheduleonce/ng-strictify/pull/49#pullrequestreview-1198977583 "Approved")*, *[SO-jagjeetsingh](https://github.com/scheduleonce/ng-strictify/pull/49#pullrequestreview-1198946135 "Approved")*, *[so-kushal](https://github.com/scheduleonce/ng-strictify/pull/49#pullrequestreview-1198900993 "Approved")*, *[so-ravindra](https://github.com/scheduleonce/ng-strictify/pull/49#pullrequestreview-1199040294 "Approved")*, *[vaibhavso](https://github.com/scheduleonce/ng-strictify/pull/49#pullrequestreview-1198986520 "Approved")*, *[vinaykumar01](https://github.com/scheduleonce/ng-strictify/pull/49#pullrequestreview-1198912162 "Approved")*

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=scheduleonce%2Fng-strictify).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/scheduleonce/ng-strictify/blob/master/OWNERS)~~ [SO-ashusrivastava,vaibhavso,vinaykumar01]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by oh-frontend** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[oh-damini](https://github.com/scheduleonce/ng-strictify/pull/49#pullrequestreview-1199116695 "Approved")*, *[oh-rahulsingla](https://github.com/scheduleonce/ng-strictify/pull/49#pullrequestreview-1199067515 "Approved")*, *[raghavaggarwalOH](https://github.com/scheduleonce/ng-strictify/pull/49#pullrequestreview-1198963497 "Approved")*, *[rameshwarverma](https://github.com/scheduleonce/ng-strictify/pull/49#pullrequestreview-1199018989 "Approved")*, *[sampada-ojha](https://github.com/scheduleonce/ng-strictify/pull/49#pullrequestreview-1198997983 "Approved")*, *[SO-ashusrivastava](https://github.com/scheduleonce/ng-strictify/pull/49#pullrequestreview-1198977583 "Approved")*, *[SO-jagjeetsingh](https://github.com/scheduleonce/ng-strictify/pull/49#pullrequestreview-1198946135 "Approved")*, *[so-kushal](https://github.com/scheduleonce/ng-strictify/pull/49#pullrequestreview-1198900993 "Approved")*, *[so-ravindra](https://github.com/scheduleonce/ng-strictify/pull/49#pullrequestreview-1199040294 "Approved")*, *[ushankar208](https://github.com/scheduleonce/ng-strictify/pull/49#issuecomment-1332078184 "Approved")*, *[vaibhavso](https://github.com/scheduleonce/ng-strictify/pull/49#pullrequestreview-1198986520 "Approved")*, *[vinaykumar01](https://github.com/scheduleonce/ng-strictify/pull/49#pullrequestreview-1198912162 "Approved")*

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=scheduleonce%2Fng-strictify).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/scheduleonce/ng-strictify/blob/master/OWNERS)~~ [SO-ashusrivastava,ushankar208,vaibhavso,vinaykumar01]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by oh-frontend** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[oh-damini](https://github.com/scheduleonce/ng-strictify/pull/49#pullrequestreview-1199116695 "Approved")*, *[oh-rahulsingla](https://github.com/scheduleonce/ng-strictify/pull/49#pullrequestreview-1199067515 "Approved")*, *[raghavaggarwalOH](https://github.com/scheduleonce/ng-strictify/pull/49#pullrequestreview-1198963497 "Approved")*, *[rameshwarverma](https://github.com/scheduleonce/ng-strictify/pull/49#pullrequestreview-1199018989 "Approved")*, *[sampada-ojha](https://github.com/scheduleonce/ng-strictify/pull/49#pullrequestreview-1198997983 "Approved")*, *[SO-ashusrivastava](https://github.com/scheduleonce/ng-strictify/pull/49#pullrequestreview-1198977583 "Approved")*, *[SO-jagjeetsingh](https://github.com/scheduleonce/ng-strictify/pull/49#pullrequestreview-1198946135 "Approved")*, *[so-kushal](https://github.com/scheduleonce/ng-strictify/pull/49#pullrequestreview-1198900993 "Approved")*, *[so-ravindra](https://github.com/scheduleonce/ng-strictify/pull/49#pullrequestreview-1199040294 "Approved")*, *[ushankar208](https://github.com/scheduleonce/ng-strictify/pull/49#issuecomment-1332078184 "Approved")*, *[vaibhavso](https://github.com/scheduleonce/ng-strictify/pull/49#pullrequestreview-1198986520 "Approved")*, *[vinaykumar01](https://github.com/scheduleonce/ng-strictify/pull/49#pullrequestreview-1198912162 "Approved")*

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=scheduleonce%2Fng-strictify).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/scheduleonce/ng-strictify/blob/master/OWNERS)~~ [SO-ashusrivastava,ushankar208,vaibhavso,vinaykumar01]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Pull request merged**
